### ISSUE TITLE
Touch cannot download the DisplayOff applet zip file from an https url

### ISSUE THREAD

**Issue by ralph-irving** [LMS-Community/applet-DisplayOff#1]
The extension.xml has https://github.com/LMS-Community/applet-DisplayOff/releases/download/v0.1/DisplayOff-v0.1.zip 
The applet installer eventually times out and reboots the touch without adding the DisplayOff applet.

**Comment by terual** [comment]
Can we host the applet on your hosting just as for the EDO applet?

**Comment by ralph-irving** [comment]
Yes.
`http://ralph.irving.sdf.org/edo/DisplayOff-v0.1.zip`
`SHA1 (DisplayOff-v0.1.zip) = c709e3d24b287132f62b3207ee7d1e9751f1bab6`

**Comment by terual** [comment]
Thanks!
